
# This file is automatically generated, you probably don't want to edit this

BinaryClassificationOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BinaryClassificationOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            disable = FALSE,
            seed = 42,
            dep = NULL,
            dep_level = NULL,
            covs = NULL,
            factors = NULL,
            stdCovs = NULL,
            encCat = NULL,
            mode = "neural_network",
            hidden_neurons_tune = "range_neurons",
            penalty_tune = "range_penalty",
            fix_n_neurons = 10,
            fix_penalty = 0.1,
            min_n_neurons = 5,
            max_n_neurons = 20,
            min_penalty = -3,
            max_penalty = 3,
            mtry_tune = "range_mtry",
            trees_tune = "range_trees",
            min_n_tune = "range_min_n",
            fix_mtry = 3,
            fix_trees = 100,
            fix_min_n = 20,
            min_mtry = 3,
            max_mtry = 8,
            min_trees = 100,
            max_trees = 300,
            min_min_n = 5,
            max_min_n = 25,
            mtryx_tune = "range_mtryx",
            treesx_tune = "range_treesx",
            min_nx_tune = "range_min_nx",
            tree_depth_tune = "range_tree_depth",
            learn_ratex_tune = "range_learn_ratex",
            loss_reduction_tune = "range_loss_reduction",
            fix_mtryx = 5,
            fix_treesx = 100,
            fix_min_nx = 20,
            fix_tree_depth = 5,
            fix_learn_ratex = 0.1,
            fix_loss_reduction = 0.1,
            min_mtryx = 3,
            max_mtryx = 8,
            min_treesx = 100,
            max_treesx = 300,
            min_min_nx = 5,
            max_min_nx = 25,
            min_tree_depth = 3,
            max_tree_depth = 8,
            min_learn_ratex = -3,
            max_learn_ratex = -1,
            min_loss_reduction = -3,
            max_loss_reduction = 1.5,
            kernels = NULL,
            cost_tune = "range_cost",
            rbf_sigma_tune = "range_rbf_sigma",
            degree_tune = "range_degree",
            scale_factor_tune = "range_scale_factor",
            fix_cost = 1,
            fix_rbf_sigma = 0.01,
            fix_degree = 2,
            fix_scale_factor = 0.1,
            min_cost = -3,
            max_cost = 3,
            min_rbf_sigma = -5,
            max_rbf_sigma = 0,
            min_degree = 1,
            max_degree = 3,
            min_scale_factor = -5,
            max_scale_factor = -1,
            tuners = "none",
            metrics = "accuracy",
            plot_tuner_results = FALSE,
            accuracy = FALSE,
            bal_accuracy = FALSE,
            precision = FALSE,
            recall = FALSE,
            specificity = FALSE,
            sensitivity = FALSE,
            kap = FALSE,
            f_meas = FALSE,
            mcc = FALSE,
            j_index = FALSE,
            detection_prevalence = FALSE,
            auc_roc = FALSE,
            pr_auc = FALSE,
            gain_capture = FALSE,
            brier_score = FALSE,
            plot_roc_curve = FALSE,
            plot_pr_curve = FALSE,
            plot_gain_curve = FALSE,
            plot_lift_curve = FALSE,
            plot_dist_by_class = FALSE,
            plot_reliability_plot = FALSE,
            plot_confusion_matrix = FALSE,
            pfi = FALSE,
            shap_mean = FALSE,
            shap_dir = FALSE,
            shap_box = FALSE,
            shap_swarm = FALSE,
            olden = FALSE,
            sobol = FALSE,
            show_shap = TRUE,
            show_olden = TRUE,
            show_sobol = TRUE, ...) {

            super$initialize(
                package="MLwrapjdev",
                name="BinaryClassification",
                requiresData=TRUE,
                ...)

            private$..disable <- jmvcore::OptionBool$new(
                "disable",
                disable,
                default=FALSE)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42)
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                rejectUnusedLevels=TRUE,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..dep_level <- jmvcore::OptionLevel$new(
                "dep_level",
                dep_level,
                variable="(dep)")
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                rejectUnusedLevels=TRUE,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..stdCovs <- jmvcore::OptionVariables$new(
                "stdCovs",
                stdCovs,
                default=NULL)
            private$..encCat <- jmvcore::OptionVariables$new(
                "encCat",
                encCat,
                default=NULL)
            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "neural_network",
                    "random_forest",
                    "xgboost",
                    "svm"),
                default="neural_network")
            private$..hidden_neurons_tune <- jmvcore::OptionList$new(
                "hidden_neurons_tune",
                hidden_neurons_tune,
                options=list(
                    "range_neurons",
                    "fix_neurons"),
                default="range_neurons")
            private$..penalty_tune <- jmvcore::OptionList$new(
                "penalty_tune",
                penalty_tune,
                options=list(
                    "range_penalty",
                    "fix_penalty"),
                default="range_penalty")
            private$..fix_n_neurons <- jmvcore::OptionInteger$new(
                "fix_n_neurons",
                fix_n_neurons,
                default=10)
            private$..fix_penalty <- jmvcore::OptionNumber$new(
                "fix_penalty",
                fix_penalty,
                default=0.1)
            private$..min_n_neurons <- jmvcore::OptionInteger$new(
                "min_n_neurons",
                min_n_neurons,
                min=1,
                max=100,
                default=5)
            private$..max_n_neurons <- jmvcore::OptionInteger$new(
                "max_n_neurons",
                max_n_neurons,
                min=5,
                max=100,
                default=20)
            private$..min_penalty <- jmvcore::OptionNumber$new(
                "min_penalty",
                min_penalty,
                min=-5,
                max=0,
                default=-3)
            private$..max_penalty <- jmvcore::OptionNumber$new(
                "max_penalty",
                max_penalty,
                min=0,
                max=5,
                default=3)
            private$..mtry_tune <- jmvcore::OptionList$new(
                "mtry_tune",
                mtry_tune,
                options=list(
                    "fix_mtry",
                    "range_mtry"),
                default="range_mtry")
            private$..trees_tune <- jmvcore::OptionList$new(
                "trees_tune",
                trees_tune,
                options=list(
                    "fix_trees",
                    "range_trees"),
                default="range_trees")
            private$..min_n_tune <- jmvcore::OptionList$new(
                "min_n_tune",
                min_n_tune,
                options=list(
                    "fix_min_n",
                    "range_min_n"),
                default="range_min_n")
            private$..fix_mtry <- jmvcore::OptionInteger$new(
                "fix_mtry",
                fix_mtry,
                default=3)
            private$..fix_trees <- jmvcore::OptionNumber$new(
                "fix_trees",
                fix_trees,
                default=100)
            private$..fix_min_n <- jmvcore::OptionInteger$new(
                "fix_min_n",
                fix_min_n,
                default=20)
            private$..min_mtry <- jmvcore::OptionInteger$new(
                "min_mtry",
                min_mtry,
                min=2,
                max=12,
                default=3)
            private$..max_mtry <- jmvcore::OptionInteger$new(
                "max_mtry",
                max_mtry,
                min=2,
                max=12,
                default=8)
            private$..min_trees <- jmvcore::OptionInteger$new(
                "min_trees",
                min_trees,
                min=50,
                max=300,
                default=100)
            private$..max_trees <- jmvcore::OptionInteger$new(
                "max_trees",
                max_trees,
                min=100,
                max=500,
                default=300)
            private$..min_min_n <- jmvcore::OptionInteger$new(
                "min_min_n",
                min_min_n,
                min=2,
                max=150,
                default=5)
            private$..max_min_n <- jmvcore::OptionInteger$new(
                "max_min_n",
                max_min_n,
                min=2,
                max=150,
                default=25)
            private$..mtryx_tune <- jmvcore::OptionList$new(
                "mtryx_tune",
                mtryx_tune,
                options=list(
                    "fix_mtryx",
                    "range_mtryx"),
                default="range_mtryx")
            private$..treesx_tune <- jmvcore::OptionList$new(
                "treesx_tune",
                treesx_tune,
                options=list(
                    "fix_treesx",
                    "range_treesx"),
                default="range_treesx")
            private$..min_nx_tune <- jmvcore::OptionList$new(
                "min_nx_tune",
                min_nx_tune,
                options=list(
                    "fix_min_nx",
                    "range_min_nx"),
                default="range_min_nx")
            private$..tree_depth_tune <- jmvcore::OptionList$new(
                "tree_depth_tune",
                tree_depth_tune,
                options=list(
                    "fix_tree_depth",
                    "range_tree_depth"),
                default="range_tree_depth")
            private$..learn_ratex_tune <- jmvcore::OptionList$new(
                "learn_ratex_tune",
                learn_ratex_tune,
                options=list(
                    "fix_learn_ratex",
                    "range_learn_ratex"),
                default="range_learn_ratex")
            private$..loss_reduction_tune <- jmvcore::OptionList$new(
                "loss_reduction_tune",
                loss_reduction_tune,
                options=list(
                    "fix_loss_reduction",
                    "range_loss_reduction"),
                default="range_loss_reduction")
            private$..fix_mtryx <- jmvcore::OptionInteger$new(
                "fix_mtryx",
                fix_mtryx,
                default=5)
            private$..fix_treesx <- jmvcore::OptionNumber$new(
                "fix_treesx",
                fix_treesx,
                default=100)
            private$..fix_min_nx <- jmvcore::OptionInteger$new(
                "fix_min_nx",
                fix_min_nx,
                default=20)
            private$..fix_tree_depth <- jmvcore::OptionInteger$new(
                "fix_tree_depth",
                fix_tree_depth,
                default=5)
            private$..fix_learn_ratex <- jmvcore::OptionNumber$new(
                "fix_learn_ratex",
                fix_learn_ratex,
                default=0.1)
            private$..fix_loss_reduction <- jmvcore::OptionNumber$new(
                "fix_loss_reduction",
                fix_loss_reduction,
                default=0.1)
            private$..min_mtryx <- jmvcore::OptionInteger$new(
                "min_mtryx",
                min_mtryx,
                min=2,
                max=12,
                default=3)
            private$..max_mtryx <- jmvcore::OptionInteger$new(
                "max_mtryx",
                max_mtryx,
                min=2,
                max=12,
                default=8)
            private$..min_treesx <- jmvcore::OptionInteger$new(
                "min_treesx",
                min_treesx,
                min=10,
                max=500,
                default=100)
            private$..max_treesx <- jmvcore::OptionInteger$new(
                "max_treesx",
                max_treesx,
                min=10,
                max=500,
                default=300)
            private$..min_min_nx <- jmvcore::OptionInteger$new(
                "min_min_nx",
                min_min_nx,
                min=2,
                max=150,
                default=5)
            private$..max_min_nx <- jmvcore::OptionInteger$new(
                "max_min_nx",
                max_min_nx,
                min=2,
                max=150,
                default=25)
            private$..min_tree_depth <- jmvcore::OptionInteger$new(
                "min_tree_depth",
                min_tree_depth,
                min=2,
                max=50,
                default=3)
            private$..max_tree_depth <- jmvcore::OptionInteger$new(
                "max_tree_depth",
                max_tree_depth,
                min=2,
                max=50,
                default=8)
            private$..min_learn_ratex <- jmvcore::OptionNumber$new(
                "min_learn_ratex",
                min_learn_ratex,
                min=-5,
                max=-0.5,
                default=-3)
            private$..max_learn_ratex <- jmvcore::OptionNumber$new(
                "max_learn_ratex",
                max_learn_ratex,
                min=-5,
                max=-0.5,
                default=-1)
            private$..min_loss_reduction <- jmvcore::OptionNumber$new(
                "min_loss_reduction",
                min_loss_reduction,
                min=-5,
                max=5,
                default=-3)
            private$..max_loss_reduction <- jmvcore::OptionNumber$new(
                "max_loss_reduction",
                max_loss_reduction,
                min=-5,
                max=5,
                default=1.5)
            private$..kernels <- jmvcore::OptionList$new(
                "kernels",
                kernels,
                options=list(
                    "linear",
                    "rbf",
                    "polynom\u00A1al"))
            private$..cost_tune <- jmvcore::OptionList$new(
                "cost_tune",
                cost_tune,
                options=list(
                    "fix_cost",
                    "range_cost"),
                default="range_cost")
            private$..rbf_sigma_tune <- jmvcore::OptionList$new(
                "rbf_sigma_tune",
                rbf_sigma_tune,
                options=list(
                    "fix_rbf_sigma",
                    "range_rbf_sigma"),
                default="range_rbf_sigma")
            private$..degree_tune <- jmvcore::OptionList$new(
                "degree_tune",
                degree_tune,
                options=list(
                    "fix_degree",
                    "range_degree"),
                default="range_degree")
            private$..scale_factor_tune <- jmvcore::OptionList$new(
                "scale_factor_tune",
                scale_factor_tune,
                options=list(
                    "fix_scale_factor",
                    "range_scale_factor"),
                default="range_scale_factor")
            private$..fix_cost <- jmvcore::OptionNumber$new(
                "fix_cost",
                fix_cost,
                default=1)
            private$..fix_rbf_sigma <- jmvcore::OptionNumber$new(
                "fix_rbf_sigma",
                fix_rbf_sigma,
                default=0.01)
            private$..fix_degree <- jmvcore::OptionNumber$new(
                "fix_degree",
                fix_degree,
                default=2)
            private$..fix_scale_factor <- jmvcore::OptionNumber$new(
                "fix_scale_factor",
                fix_scale_factor,
                default=0.1)
            private$..min_cost <- jmvcore::OptionNumber$new(
                "min_cost",
                min_cost,
                min=-10,
                max=10,
                default=-3)
            private$..max_cost <- jmvcore::OptionNumber$new(
                "max_cost",
                max_cost,
                min=-10,
                max=10,
                default=3)
            private$..min_rbf_sigma <- jmvcore::OptionNumber$new(
                "min_rbf_sigma",
                min_rbf_sigma,
                min=-6,
                max=0,
                default=-5)
            private$..max_rbf_sigma <- jmvcore::OptionNumber$new(
                "max_rbf_sigma",
                max_rbf_sigma,
                min=-6,
                max=0,
                default=0)
            private$..min_degree <- jmvcore::OptionInteger$new(
                "min_degree",
                min_degree,
                min=1,
                max=5,
                default=1)
            private$..max_degree <- jmvcore::OptionInteger$new(
                "max_degree",
                max_degree,
                min=2,
                max=5,
                default=3)
            private$..min_scale_factor <- jmvcore::OptionNumber$new(
                "min_scale_factor",
                min_scale_factor,
                min=-6,
                max=-1,
                default=-5)
            private$..max_scale_factor <- jmvcore::OptionNumber$new(
                "max_scale_factor",
                max_scale_factor,
                min=-6,
                max=-1,
                default=-1)
            private$..tuners <- jmvcore::OptionList$new(
                "tuners",
                tuners,
                options=list(
                    "none",
                    "grid_search_cv"),
                default="none")
            private$..metrics <- jmvcore::OptionList$new(
                "metrics",
                metrics,
                options=list(
                    "accuracy",
                    "bal_accuracy",
                    "precision",
                    "recall",
                    "specificity",
                    "sensitivity",
                    "kap",
                    "f_meas",
                    "mcc",
                    "j_index",
                    "detection_prevalence",
                    "roc_auc",
                    "pr_auc",
                    "gain_capture",
                    "brier_score"),
                default="accuracy")
            private$..plot_tuner_results <- jmvcore::OptionBool$new(
                "plot_tuner_results",
                plot_tuner_results,
                default=FALSE)
            private$..accuracy <- jmvcore::OptionBool$new(
                "accuracy",
                accuracy,
                default=FALSE)
            private$..bal_accuracy <- jmvcore::OptionBool$new(
                "bal_accuracy",
                bal_accuracy,
                default=FALSE)
            private$..precision <- jmvcore::OptionBool$new(
                "precision",
                precision,
                default=FALSE)
            private$..recall <- jmvcore::OptionBool$new(
                "recall",
                recall,
                default=FALSE)
            private$..specificity <- jmvcore::OptionBool$new(
                "specificity",
                specificity,
                default=FALSE)
            private$..sensitivity <- jmvcore::OptionBool$new(
                "sensitivity",
                sensitivity,
                default=FALSE)
            private$..kap <- jmvcore::OptionBool$new(
                "kap",
                kap,
                default=FALSE)
            private$..f_meas <- jmvcore::OptionBool$new(
                "f_meas",
                f_meas,
                default=FALSE)
            private$..mcc <- jmvcore::OptionBool$new(
                "mcc",
                mcc,
                default=FALSE)
            private$..j_index <- jmvcore::OptionBool$new(
                "j_index",
                j_index,
                default=FALSE)
            private$..detection_prevalence <- jmvcore::OptionBool$new(
                "detection_prevalence",
                detection_prevalence,
                default=FALSE)
            private$..auc_roc <- jmvcore::OptionBool$new(
                "auc_roc",
                auc_roc,
                default=FALSE)
            private$..pr_auc <- jmvcore::OptionBool$new(
                "pr_auc",
                pr_auc,
                default=FALSE)
            private$..gain_capture <- jmvcore::OptionBool$new(
                "gain_capture",
                gain_capture,
                default=FALSE)
            private$..brier_score <- jmvcore::OptionBool$new(
                "brier_score",
                brier_score,
                default=FALSE)
            private$..plot_roc_curve <- jmvcore::OptionBool$new(
                "plot_roc_curve",
                plot_roc_curve,
                default=FALSE)
            private$..plot_pr_curve <- jmvcore::OptionBool$new(
                "plot_pr_curve",
                plot_pr_curve,
                default=FALSE)
            private$..plot_gain_curve <- jmvcore::OptionBool$new(
                "plot_gain_curve",
                plot_gain_curve,
                default=FALSE)
            private$..plot_lift_curve <- jmvcore::OptionBool$new(
                "plot_lift_curve",
                plot_lift_curve,
                default=FALSE)
            private$..plot_dist_by_class <- jmvcore::OptionBool$new(
                "plot_dist_by_class",
                plot_dist_by_class,
                default=FALSE)
            private$..plot_reliability_plot <- jmvcore::OptionBool$new(
                "plot_reliability_plot",
                plot_reliability_plot,
                default=FALSE)
            private$..plot_confusion_matrix <- jmvcore::OptionBool$new(
                "plot_confusion_matrix",
                plot_confusion_matrix,
                default=FALSE)
            private$..pfi <- jmvcore::OptionBool$new(
                "pfi",
                pfi,
                default=FALSE)
            private$..shap_mean <- jmvcore::OptionBool$new(
                "shap_mean",
                shap_mean,
                default=FALSE)
            private$..shap_dir <- jmvcore::OptionBool$new(
                "shap_dir",
                shap_dir,
                default=FALSE)
            private$..shap_box <- jmvcore::OptionBool$new(
                "shap_box",
                shap_box,
                default=FALSE)
            private$..shap_swarm <- jmvcore::OptionBool$new(
                "shap_swarm",
                shap_swarm,
                default=FALSE)
            private$..olden <- jmvcore::OptionBool$new(
                "olden",
                olden,
                default=FALSE)
            private$..sobol <- jmvcore::OptionBool$new(
                "sobol",
                sobol,
                default=FALSE)
            private$..show_shap <- jmvcore::OptionBool$new(
                "show_shap",
                show_shap,
                hidden=TRUE,
                default=TRUE)
            private$..show_olden <- jmvcore::OptionBool$new(
                "show_olden",
                show_olden,
                hidden=TRUE,
                default=TRUE)
            private$..show_sobol <- jmvcore::OptionBool$new(
                "show_sobol",
                show_sobol,
                hidden=TRUE,
                default=TRUE)
            private$..pred_class <- jmvcore::OptionOutput$new(
                "pred_class")
            private$..pred_prob <- jmvcore::OptionOutput$new(
                "pred_prob")
            private$..dataset_id <- jmvcore::OptionOutput$new(
                "dataset_id")

            self$.addOption(private$..disable)
            self$.addOption(private$..seed)
            self$.addOption(private$..dep)
            self$.addOption(private$..dep_level)
            self$.addOption(private$..covs)
            self$.addOption(private$..factors)
            self$.addOption(private$..stdCovs)
            self$.addOption(private$..encCat)
            self$.addOption(private$..mode)
            self$.addOption(private$..hidden_neurons_tune)
            self$.addOption(private$..penalty_tune)
            self$.addOption(private$..fix_n_neurons)
            self$.addOption(private$..fix_penalty)
            self$.addOption(private$..min_n_neurons)
            self$.addOption(private$..max_n_neurons)
            self$.addOption(private$..min_penalty)
            self$.addOption(private$..max_penalty)
            self$.addOption(private$..mtry_tune)
            self$.addOption(private$..trees_tune)
            self$.addOption(private$..min_n_tune)
            self$.addOption(private$..fix_mtry)
            self$.addOption(private$..fix_trees)
            self$.addOption(private$..fix_min_n)
            self$.addOption(private$..min_mtry)
            self$.addOption(private$..max_mtry)
            self$.addOption(private$..min_trees)
            self$.addOption(private$..max_trees)
            self$.addOption(private$..min_min_n)
            self$.addOption(private$..max_min_n)
            self$.addOption(private$..mtryx_tune)
            self$.addOption(private$..treesx_tune)
            self$.addOption(private$..min_nx_tune)
            self$.addOption(private$..tree_depth_tune)
            self$.addOption(private$..learn_ratex_tune)
            self$.addOption(private$..loss_reduction_tune)
            self$.addOption(private$..fix_mtryx)
            self$.addOption(private$..fix_treesx)
            self$.addOption(private$..fix_min_nx)
            self$.addOption(private$..fix_tree_depth)
            self$.addOption(private$..fix_learn_ratex)
            self$.addOption(private$..fix_loss_reduction)
            self$.addOption(private$..min_mtryx)
            self$.addOption(private$..max_mtryx)
            self$.addOption(private$..min_treesx)
            self$.addOption(private$..max_treesx)
            self$.addOption(private$..min_min_nx)
            self$.addOption(private$..max_min_nx)
            self$.addOption(private$..min_tree_depth)
            self$.addOption(private$..max_tree_depth)
            self$.addOption(private$..min_learn_ratex)
            self$.addOption(private$..max_learn_ratex)
            self$.addOption(private$..min_loss_reduction)
            self$.addOption(private$..max_loss_reduction)
            self$.addOption(private$..kernels)
            self$.addOption(private$..cost_tune)
            self$.addOption(private$..rbf_sigma_tune)
            self$.addOption(private$..degree_tune)
            self$.addOption(private$..scale_factor_tune)
            self$.addOption(private$..fix_cost)
            self$.addOption(private$..fix_rbf_sigma)
            self$.addOption(private$..fix_degree)
            self$.addOption(private$..fix_scale_factor)
            self$.addOption(private$..min_cost)
            self$.addOption(private$..max_cost)
            self$.addOption(private$..min_rbf_sigma)
            self$.addOption(private$..max_rbf_sigma)
            self$.addOption(private$..min_degree)
            self$.addOption(private$..max_degree)
            self$.addOption(private$..min_scale_factor)
            self$.addOption(private$..max_scale_factor)
            self$.addOption(private$..tuners)
            self$.addOption(private$..metrics)
            self$.addOption(private$..plot_tuner_results)
            self$.addOption(private$..accuracy)
            self$.addOption(private$..bal_accuracy)
            self$.addOption(private$..precision)
            self$.addOption(private$..recall)
            self$.addOption(private$..specificity)
            self$.addOption(private$..sensitivity)
            self$.addOption(private$..kap)
            self$.addOption(private$..f_meas)
            self$.addOption(private$..mcc)
            self$.addOption(private$..j_index)
            self$.addOption(private$..detection_prevalence)
            self$.addOption(private$..auc_roc)
            self$.addOption(private$..pr_auc)
            self$.addOption(private$..gain_capture)
            self$.addOption(private$..brier_score)
            self$.addOption(private$..plot_roc_curve)
            self$.addOption(private$..plot_pr_curve)
            self$.addOption(private$..plot_gain_curve)
            self$.addOption(private$..plot_lift_curve)
            self$.addOption(private$..plot_dist_by_class)
            self$.addOption(private$..plot_reliability_plot)
            self$.addOption(private$..plot_confusion_matrix)
            self$.addOption(private$..pfi)
            self$.addOption(private$..shap_mean)
            self$.addOption(private$..shap_dir)
            self$.addOption(private$..shap_box)
            self$.addOption(private$..shap_swarm)
            self$.addOption(private$..olden)
            self$.addOption(private$..sobol)
            self$.addOption(private$..show_shap)
            self$.addOption(private$..show_olden)
            self$.addOption(private$..show_sobol)
            self$.addOption(private$..pred_class)
            self$.addOption(private$..pred_prob)
            self$.addOption(private$..dataset_id)
        }),
    active = list(
        disable = function() private$..disable$value,
        seed = function() private$..seed$value,
        dep = function() private$..dep$value,
        dep_level = function() private$..dep_level$value,
        covs = function() private$..covs$value,
        factors = function() private$..factors$value,
        stdCovs = function() private$..stdCovs$value,
        encCat = function() private$..encCat$value,
        mode = function() private$..mode$value,
        hidden_neurons_tune = function() private$..hidden_neurons_tune$value,
        penalty_tune = function() private$..penalty_tune$value,
        fix_n_neurons = function() private$..fix_n_neurons$value,
        fix_penalty = function() private$..fix_penalty$value,
        min_n_neurons = function() private$..min_n_neurons$value,
        max_n_neurons = function() private$..max_n_neurons$value,
        min_penalty = function() private$..min_penalty$value,
        max_penalty = function() private$..max_penalty$value,
        mtry_tune = function() private$..mtry_tune$value,
        trees_tune = function() private$..trees_tune$value,
        min_n_tune = function() private$..min_n_tune$value,
        fix_mtry = function() private$..fix_mtry$value,
        fix_trees = function() private$..fix_trees$value,
        fix_min_n = function() private$..fix_min_n$value,
        min_mtry = function() private$..min_mtry$value,
        max_mtry = function() private$..max_mtry$value,
        min_trees = function() private$..min_trees$value,
        max_trees = function() private$..max_trees$value,
        min_min_n = function() private$..min_min_n$value,
        max_min_n = function() private$..max_min_n$value,
        mtryx_tune = function() private$..mtryx_tune$value,
        treesx_tune = function() private$..treesx_tune$value,
        min_nx_tune = function() private$..min_nx_tune$value,
        tree_depth_tune = function() private$..tree_depth_tune$value,
        learn_ratex_tune = function() private$..learn_ratex_tune$value,
        loss_reduction_tune = function() private$..loss_reduction_tune$value,
        fix_mtryx = function() private$..fix_mtryx$value,
        fix_treesx = function() private$..fix_treesx$value,
        fix_min_nx = function() private$..fix_min_nx$value,
        fix_tree_depth = function() private$..fix_tree_depth$value,
        fix_learn_ratex = function() private$..fix_learn_ratex$value,
        fix_loss_reduction = function() private$..fix_loss_reduction$value,
        min_mtryx = function() private$..min_mtryx$value,
        max_mtryx = function() private$..max_mtryx$value,
        min_treesx = function() private$..min_treesx$value,
        max_treesx = function() private$..max_treesx$value,
        min_min_nx = function() private$..min_min_nx$value,
        max_min_nx = function() private$..max_min_nx$value,
        min_tree_depth = function() private$..min_tree_depth$value,
        max_tree_depth = function() private$..max_tree_depth$value,
        min_learn_ratex = function() private$..min_learn_ratex$value,
        max_learn_ratex = function() private$..max_learn_ratex$value,
        min_loss_reduction = function() private$..min_loss_reduction$value,
        max_loss_reduction = function() private$..max_loss_reduction$value,
        kernels = function() private$..kernels$value,
        cost_tune = function() private$..cost_tune$value,
        rbf_sigma_tune = function() private$..rbf_sigma_tune$value,
        degree_tune = function() private$..degree_tune$value,
        scale_factor_tune = function() private$..scale_factor_tune$value,
        fix_cost = function() private$..fix_cost$value,
        fix_rbf_sigma = function() private$..fix_rbf_sigma$value,
        fix_degree = function() private$..fix_degree$value,
        fix_scale_factor = function() private$..fix_scale_factor$value,
        min_cost = function() private$..min_cost$value,
        max_cost = function() private$..max_cost$value,
        min_rbf_sigma = function() private$..min_rbf_sigma$value,
        max_rbf_sigma = function() private$..max_rbf_sigma$value,
        min_degree = function() private$..min_degree$value,
        max_degree = function() private$..max_degree$value,
        min_scale_factor = function() private$..min_scale_factor$value,
        max_scale_factor = function() private$..max_scale_factor$value,
        tuners = function() private$..tuners$value,
        metrics = function() private$..metrics$value,
        plot_tuner_results = function() private$..plot_tuner_results$value,
        accuracy = function() private$..accuracy$value,
        bal_accuracy = function() private$..bal_accuracy$value,
        precision = function() private$..precision$value,
        recall = function() private$..recall$value,
        specificity = function() private$..specificity$value,
        sensitivity = function() private$..sensitivity$value,
        kap = function() private$..kap$value,
        f_meas = function() private$..f_meas$value,
        mcc = function() private$..mcc$value,
        j_index = function() private$..j_index$value,
        detection_prevalence = function() private$..detection_prevalence$value,
        auc_roc = function() private$..auc_roc$value,
        pr_auc = function() private$..pr_auc$value,
        gain_capture = function() private$..gain_capture$value,
        brier_score = function() private$..brier_score$value,
        plot_roc_curve = function() private$..plot_roc_curve$value,
        plot_pr_curve = function() private$..plot_pr_curve$value,
        plot_gain_curve = function() private$..plot_gain_curve$value,
        plot_lift_curve = function() private$..plot_lift_curve$value,
        plot_dist_by_class = function() private$..plot_dist_by_class$value,
        plot_reliability_plot = function() private$..plot_reliability_plot$value,
        plot_confusion_matrix = function() private$..plot_confusion_matrix$value,
        pfi = function() private$..pfi$value,
        shap_mean = function() private$..shap_mean$value,
        shap_dir = function() private$..shap_dir$value,
        shap_box = function() private$..shap_box$value,
        shap_swarm = function() private$..shap_swarm$value,
        olden = function() private$..olden$value,
        sobol = function() private$..sobol$value,
        show_shap = function() private$..show_shap$value,
        show_olden = function() private$..show_olden$value,
        show_sobol = function() private$..show_sobol$value,
        pred_class = function() private$..pred_class$value,
        pred_prob = function() private$..pred_prob$value,
        dataset_id = function() private$..dataset_id$value),
    private = list(
        ..disable = NA,
        ..seed = NA,
        ..dep = NA,
        ..dep_level = NA,
        ..covs = NA,
        ..factors = NA,
        ..stdCovs = NA,
        ..encCat = NA,
        ..mode = NA,
        ..hidden_neurons_tune = NA,
        ..penalty_tune = NA,
        ..fix_n_neurons = NA,
        ..fix_penalty = NA,
        ..min_n_neurons = NA,
        ..max_n_neurons = NA,
        ..min_penalty = NA,
        ..max_penalty = NA,
        ..mtry_tune = NA,
        ..trees_tune = NA,
        ..min_n_tune = NA,
        ..fix_mtry = NA,
        ..fix_trees = NA,
        ..fix_min_n = NA,
        ..min_mtry = NA,
        ..max_mtry = NA,
        ..min_trees = NA,
        ..max_trees = NA,
        ..min_min_n = NA,
        ..max_min_n = NA,
        ..mtryx_tune = NA,
        ..treesx_tune = NA,
        ..min_nx_tune = NA,
        ..tree_depth_tune = NA,
        ..learn_ratex_tune = NA,
        ..loss_reduction_tune = NA,
        ..fix_mtryx = NA,
        ..fix_treesx = NA,
        ..fix_min_nx = NA,
        ..fix_tree_depth = NA,
        ..fix_learn_ratex = NA,
        ..fix_loss_reduction = NA,
        ..min_mtryx = NA,
        ..max_mtryx = NA,
        ..min_treesx = NA,
        ..max_treesx = NA,
        ..min_min_nx = NA,
        ..max_min_nx = NA,
        ..min_tree_depth = NA,
        ..max_tree_depth = NA,
        ..min_learn_ratex = NA,
        ..max_learn_ratex = NA,
        ..min_loss_reduction = NA,
        ..max_loss_reduction = NA,
        ..kernels = NA,
        ..cost_tune = NA,
        ..rbf_sigma_tune = NA,
        ..degree_tune = NA,
        ..scale_factor_tune = NA,
        ..fix_cost = NA,
        ..fix_rbf_sigma = NA,
        ..fix_degree = NA,
        ..fix_scale_factor = NA,
        ..min_cost = NA,
        ..max_cost = NA,
        ..min_rbf_sigma = NA,
        ..max_rbf_sigma = NA,
        ..min_degree = NA,
        ..max_degree = NA,
        ..min_scale_factor = NA,
        ..max_scale_factor = NA,
        ..tuners = NA,
        ..metrics = NA,
        ..plot_tuner_results = NA,
        ..accuracy = NA,
        ..bal_accuracy = NA,
        ..precision = NA,
        ..recall = NA,
        ..specificity = NA,
        ..sensitivity = NA,
        ..kap = NA,
        ..f_meas = NA,
        ..mcc = NA,
        ..j_index = NA,
        ..detection_prevalence = NA,
        ..auc_roc = NA,
        ..pr_auc = NA,
        ..gain_capture = NA,
        ..brier_score = NA,
        ..plot_roc_curve = NA,
        ..plot_pr_curve = NA,
        ..plot_gain_curve = NA,
        ..plot_lift_curve = NA,
        ..plot_dist_by_class = NA,
        ..plot_reliability_plot = NA,
        ..plot_confusion_matrix = NA,
        ..pfi = NA,
        ..shap_mean = NA,
        ..shap_dir = NA,
        ..shap_box = NA,
        ..shap_swarm = NA,
        ..olden = NA,
        ..sobol = NA,
        ..show_shap = NA,
        ..show_olden = NA,
        ..show_sobol = NA,
        ..pred_class = NA,
        ..pred_prob = NA,
        ..dataset_id = NA)
)

BinaryClassificationResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BinaryClassificationResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        summary = function() private$.items[["summary"]],
        plot_tuner = function() private$.items[["plot_tuner"]],
        tuner_table = function() private$.items[["tuner_table"]],
        plots_results = function() private$.items[["plots_results"]],
        model = function() private$..model,
        plots_sensitivity = function() private$.items[["plots_sensitivity"]],
        table_sensitivity = function() private$.items[["table_sensitivity"]],
        pred_class = function() private$.items[["pred_class"]],
        pred_prob = function() private$.items[["pred_prob"]],
        dataset_id = function() private$.items[["dataset_id"]]),
    private = list(
        ..model = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Binary Classification",
                refs=list(
                    "MLwrapj",
                    "MLwrap",
                    "MLwrap_tutorial"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Binary Classification"))
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Summary Results",
                rows=2,
                clearWith=list(
                    "seed",
                    "dep",
                    "dep_level",
                    "covs",
                    "factors",
                    "stdCovs",
                    "encCat",
                    "mode",
                    "metrics",
                    "tuners",
                    "hidden_neurons_tune",
                    "fix_n_neurons",
                    "min_n_neurons",
                    "max_n_neurons",
                    "penalty_tune",
                    "fix_penalty",
                    "min_penalty",
                    "max_penalty",
                    "mtry_tune",
                    "fix_mtry",
                    "min_mtry",
                    "max_mtry",
                    "trees_tune",
                    "fix_trees",
                    "min_trees",
                    "max_trees",
                    "min_n_tune",
                    "fix_min_n",
                    "min_min_n",
                    "max_min_n",
                    "mtryx_tune",
                    "fix_mtryx",
                    "min_mtryx",
                    "max_mtryx",
                    "treesx_tune",
                    "fix_treesx",
                    "min_treesx",
                    "max_treesx",
                    "min_nx_tune",
                    "fix_min_nx",
                    "min_min_nx",
                    "max_min_nx",
                    "tree_depth_tune",
                    "fix_tree_depth",
                    "min_tree_depth",
                    "max_tree_depth",
                    "learn_ratex_tune",
                    "fix_learn_ratex",
                    "min_learn_ratex",
                    "max_learn_ratex",
                    "loss_reduction_tune",
                    "fix_loss_reduction",
                    "min_loss_reduction",
                    "max_loss_reduction",
                    "kernels",
                    "cost_tune",
                    "fix_cost",
                    "min_cost",
                    "max_cost",
                    "rbf_sigma_tune",
                    "fix_rbf_sigma",
                    "min_rbf_sigma",
                    "max_rbf_sigma",
                    "degree_tune",
                    "fix_degree",
                    "min_degree",
                    "max_degree",
                    "scale_factor_tune",
                    "fix_scale_factor",
                    "min_scale_factor",
                    "max_scale_factor"),
                columns=list(
                    list(
                        `name`="Dataset", 
                        `title`="Dataset", 
                        `type`="text"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="plot_tuner",
                title="Tuning Results",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    width=500,
                    height=400,
                    renderFun=".plot_tuner",
                    clearWith=list(
                        "seed",
                        "dep",
                        "dep_level",
                        "covs",
                        "factors",
                        "stdCovs",
                        "encCat",
                        "mode",
                        "metrics",
                        "tuners",
                        "hidden_neurons_tune",
                        "fix_n_neurons",
                        "min_n_neurons",
                        "max_n_neurons",
                        "penalty_tune",
                        "fix_penalty",
                        "min_penalty",
                        "max_penalty",
                        "mtry_tune",
                        "fix_mtry",
                        "min_mtry",
                        "max_mtry",
                        "trees_tune",
                        "fix_trees",
                        "min_trees",
                        "max_trees",
                        "min_n_tune",
                        "fix_min_n",
                        "min_min_n",
                        "max_min_n",
                        "mtryx_tune",
                        "fix_mtryx",
                        "min_mtryx",
                        "max_mtryx",
                        "treesx_tune",
                        "fix_treesx",
                        "min_treesx",
                        "max_treesx",
                        "min_nx_tune",
                        "fix_min_nx",
                        "min_min_nx",
                        "max_min_nx",
                        "tree_depth_tune",
                        "fix_tree_depth",
                        "min_tree_depth",
                        "max_tree_depth",
                        "learn_ratex_tune",
                        "fix_learn_ratex",
                        "min_learn_ratex",
                        "max_learn_ratex",
                        "loss_reduction_tune",
                        "fix_loss_reduction",
                        "min_loss_reduction",
                        "max_loss_reduction",
                        "kernels",
                        "cost_tune",
                        "fix_cost",
                        "min_cost",
                        "max_cost",
                        "rbf_sigma_tune",
                        "fix_rbf_sigma",
                        "min_rbf_sigma",
                        "max_rbf_sigma",
                        "degree_tune",
                        "fix_degree",
                        "min_degree",
                        "max_degree",
                        "scale_factor_tune",
                        "fix_scale_factor",
                        "min_scale_factor",
                        "max_scale_factor"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="tuner_table",
                title="Best Hyperparameters",
                template=jmvcore::Table$new(
                    options=options,
                    title="$key",
                    rows=1,
                    columns=list(
                        list(
                            `name`="metric", 
                            `title`="Metric", 
                            `type`="text"),
                        list(
                            `name`="estimate", 
                            `title`="Estimate", 
                            `type`="number"),
                        list(
                            `name`="std", 
                            `title`="Std Err", 
                            `type`="number")))))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots_results",
                title="Results Plots",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    width=500,
                    height=400,
                    renderFun=".plot_result",
                    clearWith=list(
                        "seed",
                        "dep",
                        "dep_level",
                        "covs",
                        "factors",
                        "stdCovs",
                        "encCat",
                        "mode",
                        "metrics",
                        "tuners",
                        "hidden_neurons_tune",
                        "fix_n_neurons",
                        "min_n_neurons",
                        "max_n_neurons",
                        "penalty_tune",
                        "fix_penalty",
                        "min_penalty",
                        "max_penalty",
                        "mtry_tune",
                        "fix_mtry",
                        "min_mtry",
                        "max_mtry",
                        "trees_tune",
                        "fix_trees",
                        "min_trees",
                        "max_trees",
                        "min_n_tune",
                        "fix_min_n",
                        "min_min_n",
                        "max_min_n",
                        "mtryx_tune",
                        "fix_mtryx",
                        "min_mtryx",
                        "max_mtryx",
                        "treesx_tune",
                        "fix_treesx",
                        "min_treesx",
                        "max_treesx",
                        "min_nx_tune",
                        "fix_min_nx",
                        "min_min_nx",
                        "max_min_nx",
                        "tree_depth_tune",
                        "fix_tree_depth",
                        "min_tree_depth",
                        "max_tree_depth",
                        "learn_ratex_tune",
                        "fix_learn_ratex",
                        "min_learn_ratex",
                        "max_learn_ratex",
                        "loss_reduction_tune",
                        "fix_loss_reduction",
                        "min_loss_reduction",
                        "max_loss_reduction",
                        "kernels",
                        "cost_tune",
                        "fix_cost",
                        "min_cost",
                        "max_cost",
                        "rbf_sigma_tune",
                        "fix_rbf_sigma",
                        "min_rbf_sigma",
                        "max_rbf_sigma",
                        "degree_tune",
                        "fix_degree",
                        "min_degree",
                        "max_degree",
                        "scale_factor_tune",
                        "fix_scale_factor",
                        "min_scale_factor",
                        "max_scale_factor"))))
            private$..model <- NULL
            self$add(jmvcore::Array$new(
                options=options,
                name="plots_sensitivity",
                title="Sensitivity Analysis Plots",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    width=500,
                    height=400,
                    renderFun=".plot_sensitivity",
                    clearWith=list(
                        "seed",
                        "dep",
                        "dep_level",
                        "covs",
                        "factors",
                        "stdCovs",
                        "encCat",
                        "mode",
                        "metrics",
                        "tuners",
                        "hidden_neurons_tune",
                        "fix_n_neurons",
                        "min_n_neurons",
                        "max_n_neurons",
                        "penalty_tune",
                        "fix_penalty",
                        "min_penalty",
                        "max_penalty",
                        "mtry_tune",
                        "fix_mtry",
                        "min_mtry",
                        "max_mtry",
                        "trees_tune",
                        "fix_trees",
                        "min_trees",
                        "max_trees",
                        "min_n_tune",
                        "fix_min_n",
                        "min_min_n",
                        "max_min_n",
                        "mtryx_tune",
                        "fix_mtryx",
                        "min_mtryx",
                        "max_mtryx",
                        "treesx_tune",
                        "fix_treesx",
                        "min_treesx",
                        "max_treesx",
                        "min_nx_tune",
                        "fix_min_nx",
                        "min_min_nx",
                        "max_min_nx",
                        "tree_depth_tune",
                        "fix_tree_depth",
                        "min_tree_depth",
                        "max_tree_depth",
                        "learn_ratex_tune",
                        "fix_learn_ratex",
                        "min_learn_ratex",
                        "max_learn_ratex",
                        "loss_reduction_tune",
                        "fix_loss_reduction",
                        "min_loss_reduction",
                        "max_loss_reduction",
                        "kernels",
                        "cost_tune",
                        "fix_cost",
                        "min_cost",
                        "max_cost",
                        "rbf_sigma_tune",
                        "fix_rbf_sigma",
                        "min_rbf_sigma",
                        "max_rbf_sigma",
                        "degree_tune",
                        "fix_degree",
                        "min_degree",
                        "max_degree",
                        "scale_factor_tune",
                        "fix_scale_factor",
                        "min_scale_factor",
                        "max_scale_factor"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="table_sensitivity",
                title="Sensitivity Analysis Tables",
                template=jmvcore::Table$new(
                    options=options,
                    title="$key",
                    clearWith=list(
                        "seed",
                        "dep",
                        "dep_level",
                        "covs",
                        "factors",
                        "stdCovs",
                        "encCat",
                        "mode",
                        "metrics",
                        "tuners",
                        "hidden_neurons_tune",
                        "fix_n_neurons",
                        "min_n_neurons",
                        "max_n_neurons",
                        "penalty_tune",
                        "fix_penalty",
                        "min_penalty",
                        "max_penalty",
                        "mtry_tune",
                        "fix_mtry",
                        "min_mtry",
                        "max_mtry",
                        "trees_tune",
                        "fix_trees",
                        "min_trees",
                        "max_trees",
                        "min_n_tune",
                        "fix_min_n",
                        "min_min_n",
                        "max_min_n",
                        "mtryx_tune",
                        "fix_mtryx",
                        "min_mtryx",
                        "max_mtryx",
                        "treesx_tune",
                        "fix_treesx",
                        "min_treesx",
                        "max_treesx",
                        "min_nx_tune",
                        "fix_min_nx",
                        "min_min_nx",
                        "max_min_nx",
                        "tree_depth_tune",
                        "fix_tree_depth",
                        "min_tree_depth",
                        "max_tree_depth",
                        "learn_ratex_tune",
                        "fix_learn_ratex",
                        "min_learn_ratex",
                        "max_learn_ratex",
                        "loss_reduction_tune",
                        "fix_loss_reduction",
                        "min_loss_reduction",
                        "max_loss_reduction",
                        "kernels",
                        "cost_tune",
                        "fix_cost",
                        "min_cost",
                        "max_cost",
                        "rbf_sigma_tune",
                        "fix_rbf_sigma",
                        "min_rbf_sigma",
                        "max_rbf_sigma",
                        "degree_tune",
                        "fix_degree",
                        "min_degree",
                        "max_degree",
                        "scale_factor_tune",
                        "fix_scale_factor",
                        "min_scale_factor",
                        "max_scale_factor"),
                    columns=list(
                        list(
                            `name`="var", 
                            `title`="Feature", 
                            `type`="text")))))
            self$add(jmvcore::Output$new(
                options=options,
                name="pred_class",
                title="Predicted Class",
                varTitle="Predicted Class",
                varDescription="Predicted Class from Binary Classification",
                measureType="nominal",
                clearWith=list(
                    "seed",
                    "dep",
                    "dep_level",
                    "covs",
                    "factors",
                    "stdCovs",
                    "encCat",
                    "mode",
                    "metrics",
                    "tuners",
                    "hidden_neurons_tune",
                    "fix_n_neurons",
                    "min_n_neurons",
                    "max_n_neurons",
                    "penalty_tune",
                    "fix_penalty",
                    "min_penalty",
                    "max_penalty",
                    "mtry_tune",
                    "fix_mtry",
                    "min_mtry",
                    "max_mtry",
                    "trees_tune",
                    "fix_trees",
                    "min_trees",
                    "max_trees",
                    "min_n_tune",
                    "fix_min_n",
                    "min_min_n",
                    "max_min_n",
                    "mtryx_tune",
                    "fix_mtryx",
                    "min_mtryx",
                    "max_mtryx",
                    "treesx_tune",
                    "fix_treesx",
                    "min_treesx",
                    "max_treesx",
                    "min_nx_tune",
                    "fix_min_nx",
                    "min_min_nx",
                    "max_min_nx",
                    "tree_depth_tune",
                    "fix_tree_depth",
                    "min_tree_depth",
                    "max_tree_depth",
                    "learn_ratex_tune",
                    "fix_learn_ratex",
                    "min_learn_ratex",
                    "max_learn_ratex",
                    "loss_reduction_tune",
                    "fix_loss_reduction",
                    "min_loss_reduction",
                    "max_loss_reduction",
                    "kernels",
                    "cost_tune",
                    "fix_cost",
                    "min_cost",
                    "max_cost",
                    "rbf_sigma_tune",
                    "fix_rbf_sigma",
                    "min_rbf_sigma",
                    "max_rbf_sigma",
                    "degree_tune",
                    "fix_degree",
                    "min_degree",
                    "max_degree",
                    "scale_factor_tune",
                    "fix_scale_factor",
                    "min_scale_factor",
                    "max_scale_factor")))
            self$add(jmvcore::Output$new(
                options=options,
                name="pred_prob",
                title="Predicted Positive Class Probability",
                varTitle="Predicted Probability",
                varDescription="Predicted Positive Probability from Binary Classification",
                measureType="continuous",
                clearWith=list(
                    "seed",
                    "dep",
                    "dep_level",
                    "covs",
                    "factors",
                    "stdCovs",
                    "encCat",
                    "mode",
                    "metrics",
                    "tuners",
                    "hidden_neurons_tune",
                    "fix_n_neurons",
                    "min_n_neurons",
                    "max_n_neurons",
                    "penalty_tune",
                    "fix_penalty",
                    "min_penalty",
                    "max_penalty",
                    "mtry_tune",
                    "fix_mtry",
                    "min_mtry",
                    "max_mtry",
                    "trees_tune",
                    "fix_trees",
                    "min_trees",
                    "max_trees",
                    "min_n_tune",
                    "fix_min_n",
                    "min_min_n",
                    "max_min_n",
                    "mtryx_tune",
                    "fix_mtryx",
                    "min_mtryx",
                    "max_mtryx",
                    "treesx_tune",
                    "fix_treesx",
                    "min_treesx",
                    "max_treesx",
                    "min_nx_tune",
                    "fix_min_nx",
                    "min_min_nx",
                    "max_min_nx",
                    "tree_depth_tune",
                    "fix_tree_depth",
                    "min_tree_depth",
                    "max_tree_depth",
                    "learn_ratex_tune",
                    "fix_learn_ratex",
                    "min_learn_ratex",
                    "max_learn_ratex",
                    "loss_reduction_tune",
                    "fix_loss_reduction",
                    "min_loss_reduction",
                    "max_loss_reduction",
                    "kernels",
                    "cost_tune",
                    "fix_cost",
                    "min_cost",
                    "max_cost",
                    "rbf_sigma_tune",
                    "fix_rbf_sigma",
                    "min_rbf_sigma",
                    "max_rbf_sigma",
                    "degree_tune",
                    "fix_degree",
                    "min_degree",
                    "max_degree",
                    "scale_factor_tune",
                    "fix_scale_factor",
                    "min_scale_factor",
                    "max_scale_factor")))
            self$add(jmvcore::Output$new(
                options=options,
                name="dataset_id",
                title="Train/Test Label",
                varTitle="Train/Test Label",
                varDescription="Train/Test label for model pipeline",
                measureType="nominal",
                clearWith=list(
                    "seed",
                    "dep",
                    "dep_level",
                    "covs",
                    "factors",
                    "stdCovs",
                    "encCat",
                    "mode",
                    "metrics",
                    "tuners",
                    "hidden_neurons_tune",
                    "fix_n_neurons",
                    "min_n_neurons",
                    "max_n_neurons",
                    "penalty_tune",
                    "fix_penalty",
                    "min_penalty",
                    "max_penalty",
                    "mtry_tune",
                    "fix_mtry",
                    "min_mtry",
                    "max_mtry",
                    "trees_tune",
                    "fix_trees",
                    "min_trees",
                    "max_trees",
                    "min_n_tune",
                    "fix_min_n",
                    "min_min_n",
                    "max_min_n",
                    "mtryx_tune",
                    "fix_mtryx",
                    "min_mtryx",
                    "max_mtryx",
                    "treesx_tune",
                    "fix_treesx",
                    "min_treesx",
                    "max_treesx",
                    "min_nx_tune",
                    "fix_min_nx",
                    "min_min_nx",
                    "max_min_nx",
                    "tree_depth_tune",
                    "fix_tree_depth",
                    "min_tree_depth",
                    "max_tree_depth",
                    "learn_ratex_tune",
                    "fix_learn_ratex",
                    "min_learn_ratex",
                    "max_learn_ratex",
                    "loss_reduction_tune",
                    "fix_loss_reduction",
                    "min_loss_reduction",
                    "max_loss_reduction",
                    "kernels",
                    "cost_tune",
                    "fix_cost",
                    "min_cost",
                    "max_cost",
                    "rbf_sigma_tune",
                    "fix_rbf_sigma",
                    "min_rbf_sigma",
                    "max_rbf_sigma",
                    "degree_tune",
                    "fix_degree",
                    "min_degree",
                    "max_degree",
                    "scale_factor_tune",
                    "fix_scale_factor",
                    "min_scale_factor",
                    "max_scale_factor")))},
        .setModel=function(x) private$..model <- x))

BinaryClassificationBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BinaryClassificationBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MLwrapjdev",
                name = "BinaryClassification",
                version = c(1,0,0),
                options = options,
                results = BinaryClassificationResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Binary Classification
#'
#' Linear regression is used to explore the relationship between a continuous 
#' dependent variable, and one or more continuous and/or categorical 
#' explanatory variables. Other statistical methods, such as ANOVA and ANCOVA, 
#' are in reality just forms of linear regression.
#' 
#' @param disable .
#' @param seed .
#' @param data the data as a data frame
#' @param dep the fixed factors from \code{data}
#' @param dep_level The level of the outcome variable that represents the
#'   event of interest.
#' @param covs the covariates from \code{data}
#' @param factors the fixed factors from \code{data}
#' @param stdCovs .
#' @param encCat .
#' @param mode .
#' @param hidden_neurons_tune .
#' @param penalty_tune .
#' @param fix_n_neurons .
#' @param fix_penalty .
#' @param min_n_neurons a number between 50 and 99.9 (default: 95) specifying
#'   the confidence interval width
#' @param max_n_neurons a number between 50 and 99.9 (default: 95) specifying
#'   the confidence interval width
#' @param min_penalty log10()
#' @param max_penalty log10()
#' @param mtry_tune .
#' @param trees_tune .
#' @param min_n_tune .
#' @param fix_mtry .
#' @param fix_trees .
#' @param fix_min_n .
#' @param min_mtry a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width
#' @param max_mtry a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width
#' @param min_trees a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width
#' @param max_trees a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width
#' @param min_min_n a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width
#' @param max_min_n a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width
#' @param mtryx_tune .
#' @param treesx_tune .
#' @param min_nx_tune .
#' @param tree_depth_tune .
#' @param learn_ratex_tune .
#' @param loss_reduction_tune .
#' @param fix_mtryx .
#' @param fix_treesx .
#' @param fix_min_nx .
#' @param fix_tree_depth .
#' @param fix_learn_ratex .
#' @param fix_loss_reduction .
#' @param min_mtryx a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width
#' @param max_mtryx a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width
#' @param min_treesx a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width
#' @param max_treesx a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width
#' @param min_min_nx a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width
#' @param max_min_nx a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width
#' @param min_tree_depth a number between 50 and 99.9 (default: 95) specifying
#'   the confidence interval width
#' @param max_tree_depth a number between 50 and 99.9 (default: 95) specifying
#'   the confidence interval width
#' @param min_learn_ratex log10()
#' @param max_learn_ratex log10()
#' @param min_loss_reduction log10()
#' @param max_loss_reduction log10()
#' @param kernels .
#' @param cost_tune .
#' @param rbf_sigma_tune .
#' @param degree_tune .
#' @param scale_factor_tune .
#' @param fix_cost .
#' @param fix_rbf_sigma .
#' @param fix_degree .
#' @param fix_scale_factor .
#' @param min_cost log2()
#' @param max_cost log2()
#' @param min_rbf_sigma log10()
#' @param max_rbf_sigma log10()
#' @param min_degree a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width
#' @param max_degree a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width
#' @param min_scale_factor log10()
#' @param max_scale_factor log10()
#' @param tuners .
#' @param metrics .
#' @param plot_tuner_results .
#' @param accuracy .
#' @param bal_accuracy .
#' @param precision .
#' @param recall .
#' @param specificity .
#' @param sensitivity .
#' @param kap .
#' @param f_meas .
#' @param mcc .
#' @param j_index .
#' @param detection_prevalence .
#' @param auc_roc .
#' @param pr_auc .
#' @param gain_capture .
#' @param brier_score .
#' @param plot_roc_curve .
#' @param plot_pr_curve .
#' @param plot_gain_curve .
#' @param plot_lift_curve .
#' @param plot_dist_by_class .
#' @param plot_reliability_plot .
#' @param plot_confusion_matrix .
#' @param pfi .
#' @param shap_mean .
#' @param shap_dir .
#' @param shap_box .
#' @param shap_swarm .
#' @param olden .
#' @param sobol .
#' @param show_shap .
#' @param show_olden .
#' @param show_sobol .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot_tuner} \tab \tab \tab \tab \tab tuner plots \cr
#'   \code{results$tuner_table} \tab \tab \tab \tab \tab tuner table results \cr
#'   \code{results$plots_results} \tab \tab \tab \tab \tab an array of plots \cr
#'   \code{results$model} \tab \tab \tab \tab \tab The underlying \code{aov} object \cr
#'   \code{results$plots_sensitivity} \tab \tab \tab \tab \tab an array of plots \cr
#'   \code{results$table_sensitivity} \tab \tab \tab \tab \tab an array of plots \cr
#'   \code{results$pred_class} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$pred_prob} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$dataset_id} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
BinaryClassification <- function(
    disable = FALSE,
    seed = 42,
    data,
    dep = NULL,
    dep_level,
    covs = NULL,
    factors = NULL,
    stdCovs = NULL,
    encCat = NULL,
    mode = "neural_network",
    hidden_neurons_tune = "range_neurons",
    penalty_tune = "range_penalty",
    fix_n_neurons = 10,
    fix_penalty = 0.1,
    min_n_neurons = 5,
    max_n_neurons = 20,
    min_penalty = -3,
    max_penalty = 3,
    mtry_tune = "range_mtry",
    trees_tune = "range_trees",
    min_n_tune = "range_min_n",
    fix_mtry = 3,
    fix_trees = 100,
    fix_min_n = 20,
    min_mtry = 3,
    max_mtry = 8,
    min_trees = 100,
    max_trees = 300,
    min_min_n = 5,
    max_min_n = 25,
    mtryx_tune = "range_mtryx",
    treesx_tune = "range_treesx",
    min_nx_tune = "range_min_nx",
    tree_depth_tune = "range_tree_depth",
    learn_ratex_tune = "range_learn_ratex",
    loss_reduction_tune = "range_loss_reduction",
    fix_mtryx = 5,
    fix_treesx = 100,
    fix_min_nx = 20,
    fix_tree_depth = 5,
    fix_learn_ratex = 0.1,
    fix_loss_reduction = 0.1,
    min_mtryx = 3,
    max_mtryx = 8,
    min_treesx = 100,
    max_treesx = 300,
    min_min_nx = 5,
    max_min_nx = 25,
    min_tree_depth = 3,
    max_tree_depth = 8,
    min_learn_ratex = -3,
    max_learn_ratex = -1,
    min_loss_reduction = -3,
    max_loss_reduction = 1.5,
    kernels,
    cost_tune = "range_cost",
    rbf_sigma_tune = "range_rbf_sigma",
    degree_tune = "range_degree",
    scale_factor_tune = "range_scale_factor",
    fix_cost = 1,
    fix_rbf_sigma = 0.01,
    fix_degree = 2,
    fix_scale_factor = 0.1,
    min_cost = -3,
    max_cost = 3,
    min_rbf_sigma = -5,
    max_rbf_sigma = 0,
    min_degree = 1,
    max_degree = 3,
    min_scale_factor = -5,
    max_scale_factor = -1,
    tuners = "none",
    metrics = "accuracy",
    plot_tuner_results = FALSE,
    accuracy = FALSE,
    bal_accuracy = FALSE,
    precision = FALSE,
    recall = FALSE,
    specificity = FALSE,
    sensitivity = FALSE,
    kap = FALSE,
    f_meas = FALSE,
    mcc = FALSE,
    j_index = FALSE,
    detection_prevalence = FALSE,
    auc_roc = FALSE,
    pr_auc = FALSE,
    gain_capture = FALSE,
    brier_score = FALSE,
    plot_roc_curve = FALSE,
    plot_pr_curve = FALSE,
    plot_gain_curve = FALSE,
    plot_lift_curve = FALSE,
    plot_dist_by_class = FALSE,
    plot_reliability_plot = FALSE,
    plot_confusion_matrix = FALSE,
    pfi = FALSE,
    shap_mean = FALSE,
    shap_dir = FALSE,
    shap_box = FALSE,
    shap_swarm = FALSE,
    olden = FALSE,
    sobol = FALSE,
    show_shap = TRUE,
    show_olden = TRUE,
    show_sobol = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("BinaryClassification requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if ( ! missing(stdCovs)) stdCovs <- jmvcore::resolveQuo(jmvcore::enquo(stdCovs))
    if ( ! missing(encCat)) encCat <- jmvcore::resolveQuo(jmvcore::enquo(encCat))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(factors), factors, NULL),
            `if`( ! missing(stdCovs), stdCovs, NULL),
            `if`( ! missing(encCat), encCat, NULL))

    for (v in dep) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- BinaryClassificationOptions$new(
        disable = disable,
        seed = seed,
        dep = dep,
        dep_level = dep_level,
        covs = covs,
        factors = factors,
        stdCovs = stdCovs,
        encCat = encCat,
        mode = mode,
        hidden_neurons_tune = hidden_neurons_tune,
        penalty_tune = penalty_tune,
        fix_n_neurons = fix_n_neurons,
        fix_penalty = fix_penalty,
        min_n_neurons = min_n_neurons,
        max_n_neurons = max_n_neurons,
        min_penalty = min_penalty,
        max_penalty = max_penalty,
        mtry_tune = mtry_tune,
        trees_tune = trees_tune,
        min_n_tune = min_n_tune,
        fix_mtry = fix_mtry,
        fix_trees = fix_trees,
        fix_min_n = fix_min_n,
        min_mtry = min_mtry,
        max_mtry = max_mtry,
        min_trees = min_trees,
        max_trees = max_trees,
        min_min_n = min_min_n,
        max_min_n = max_min_n,
        mtryx_tune = mtryx_tune,
        treesx_tune = treesx_tune,
        min_nx_tune = min_nx_tune,
        tree_depth_tune = tree_depth_tune,
        learn_ratex_tune = learn_ratex_tune,
        loss_reduction_tune = loss_reduction_tune,
        fix_mtryx = fix_mtryx,
        fix_treesx = fix_treesx,
        fix_min_nx = fix_min_nx,
        fix_tree_depth = fix_tree_depth,
        fix_learn_ratex = fix_learn_ratex,
        fix_loss_reduction = fix_loss_reduction,
        min_mtryx = min_mtryx,
        max_mtryx = max_mtryx,
        min_treesx = min_treesx,
        max_treesx = max_treesx,
        min_min_nx = min_min_nx,
        max_min_nx = max_min_nx,
        min_tree_depth = min_tree_depth,
        max_tree_depth = max_tree_depth,
        min_learn_ratex = min_learn_ratex,
        max_learn_ratex = max_learn_ratex,
        min_loss_reduction = min_loss_reduction,
        max_loss_reduction = max_loss_reduction,
        kernels = kernels,
        cost_tune = cost_tune,
        rbf_sigma_tune = rbf_sigma_tune,
        degree_tune = degree_tune,
        scale_factor_tune = scale_factor_tune,
        fix_cost = fix_cost,
        fix_rbf_sigma = fix_rbf_sigma,
        fix_degree = fix_degree,
        fix_scale_factor = fix_scale_factor,
        min_cost = min_cost,
        max_cost = max_cost,
        min_rbf_sigma = min_rbf_sigma,
        max_rbf_sigma = max_rbf_sigma,
        min_degree = min_degree,
        max_degree = max_degree,
        min_scale_factor = min_scale_factor,
        max_scale_factor = max_scale_factor,
        tuners = tuners,
        metrics = metrics,
        plot_tuner_results = plot_tuner_results,
        accuracy = accuracy,
        bal_accuracy = bal_accuracy,
        precision = precision,
        recall = recall,
        specificity = specificity,
        sensitivity = sensitivity,
        kap = kap,
        f_meas = f_meas,
        mcc = mcc,
        j_index = j_index,
        detection_prevalence = detection_prevalence,
        auc_roc = auc_roc,
        pr_auc = pr_auc,
        gain_capture = gain_capture,
        brier_score = brier_score,
        plot_roc_curve = plot_roc_curve,
        plot_pr_curve = plot_pr_curve,
        plot_gain_curve = plot_gain_curve,
        plot_lift_curve = plot_lift_curve,
        plot_dist_by_class = plot_dist_by_class,
        plot_reliability_plot = plot_reliability_plot,
        plot_confusion_matrix = plot_confusion_matrix,
        pfi = pfi,
        shap_mean = shap_mean,
        shap_dir = shap_dir,
        shap_box = shap_box,
        shap_swarm = shap_swarm,
        olden = olden,
        sobol = sobol,
        show_shap = show_shap,
        show_olden = show_olden,
        show_sobol = show_sobol)

    analysis <- BinaryClassificationClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

